### ISSUE TITLE
Environments not found in robosuite

### ISSUE THREAD

**Issue by elin-bdai** [NVlabs/mimicgen#18]
In the newer updates, I am getting this error when trying running:

```
env = EnvUtils.create_env_from_metadata(
    env_meta=env_meta, 
    render=False,            # no on-screen rendering
    render_offscreen=True,   # off-screen rendering to support rendering video frames
)
```
Error message:
```
`Exception: Environment Coffee_D0 not found. Make sure it is a registered environment among: Lift, Stack, NutAssembly, NutAssemblySingle, NutAssemblySquare, NutAssemblyRound, PickPlace, PickPlaceSingle, PickPlaceMilk, PickPlaceBread, PickPlaceCereal, PickPlaceCan, Door, Wipe, ToolHang, TwoArmLift, TwoArmPegInHole, TwoArmHandover, TwoArmTransport`
```

It works fine with an older commit: 45db4b35a5a79e82ca8a70ce1321f855498ca82c

I don't see any documentation with an updated API. Is there something I have to change in how I setup the environment?

Thank you!

**Comment by amandlek** [comment]
My best guess is that you had a `import mimicgen_envs` line that needs to now change to `import mimicgen`, since the module name changed.

**Comment by elin-bdai** [comment]
Ah, I see. It must be this one: https://github.com/ARISE-Initiative/robomimic/blob/master/robomimic/envs/env_robosuite.py#L14. Will make a PR over there. Thanks!

**Comment by amandlek** [comment]
Thanks for pointing this out! Should be fixed once this PR is merged: https://github.com/ARISE-Initiative/robomimic/pull/176
