### ISSUE TITLE
Coffee environment has error

### ISSUE THREAD

**Issue by Pingcheng-Jian** [NVlabs/mimicgen#19]
Hi,

I was trying to train in the Coffee_D0 environment, then I got this error:

File "/mimicgen/mimicgen/envs/robosuite/coffee.py", line 267, in _load_model
    self.coffee_machine = CoffeeMachineObject(name="coffee_machine")
  File "/mimicgen/mimicgen/models/robosuite/objects/composite_body/coffee_machine.py", line 29, in __init__
    body_size = body.get_bounding_box_half_size()
AttributeError: 'CoffeeMachineBodyObject' object has no attribute 'get_bounding_box_half_size'

Why it happens? How to solve it?

**Comment by amandlek** [comment]
My best guess is that your robosuite version is too old - can you try with the latest master branch? This PR [here](https://github.com/ARISE-Initiative/robosuite/pull/420) merged in some changes needed for MimicGen.
