### ISSUE TITLE
Dataset for Isaac Gym Environments

### ISSUE THREAD

**Issue by hukz18** [NVlabs/mimicgen#20]
Hi there, Thanks for your wonderful work! Is it possible to release the dataset for the IsaacGem Factory tasks as well, as there are currently only Mujoco tasks on the HuggingFace dataset page. It will surely boost the diversity and coverage of the dataset provided.

**Comment by amandlek** [comment]
Unfortunately releasing the datasets for the IsaacGym Factory tasks would also require releasing the simulation environments themselves, which we are unable to do at this point in time.
