### ISSUE TITLE
Function undefined

### ISSUE THREAD

**Issue by yunshengtian** [NVlabs/mimicgen#23]
Hi, thank you for releasing the great repo!

It seems like this function (visualize_trajectory_with_obs) is undefined in visualizing subtasks: https://github.com/NVlabs/mimicgen/blob/ea0988523f468ccf7570475f1906023f854962e9/mimicgen/scripts/visualize_subtasks.py#L258C13-L258C42

Could you fix it? Much appreciated.

**Comment by amandlek** [comment]
I believe I have fixed the issue - can you verify it works for you? See this [PR](https://github.com/NVlabs/mimicgen/pull/24). If it works I will go ahead and merge it.

**Comment by yunshengtian** [comment]
Hi @amandlek thanks for your prompt response! I think there are still variables undefined here (stage_signal and vis_stage_inds) in the updated function https://github.com/NVlabs/mimicgen/blob/9922b6be2b3de92e08a7f678ad058b8ef836960f/mimicgen/scripts/visualize_subtasks.py#L140

**Comment by amandlek** [comment]
Sorry about that - updated.

**Comment by yunshengtian** [comment]
Awesome. Thank you so much!

**Comment by amandlek** [comment]
Addressed by #24
