### ISSUE TITLE
How to connect Mimicgen with Isaac sim?

### ISSUE THREAD

**Issue by GuaguaguaLiu** [NVlabs/mimicgen#25]
Thanks for your great work!

I've noticed that MimicGen is currently used to process raw data collected from the MuJoCo simulation environment. If I want to collect HDF5 raw data in Isaac Sim, can I still use MimicGen for processing? If so, could you guide me on how to do this? 

I've made some initial attempts but found that Isaac Sim seems to lack a clear definition of `simulator state` and does not have a function similar to `set_state_from_flattened` in mujoco-py. As a result, when trying the first step of using MimicGen, which is `prepare_src_dataset.py`, I'm unsure how to set the Isaac simulator to a specific state. Do you have any suggestions on how to address this?

Look forward to your reply！ Thank you!

**Comment by amandlek** [comment]
In principle MimicGen should work for your custom Isaac Sim environment but it requires implementing an environment interface for MimicGen and a environment wrapper for robomimic. See more information [here](https://mimicgen.github.io/docs/tutorials/datagen_custom.html#generating-data-for-new-simulation-frameworks).

**Comment by GuaguaguaLiu** [comment]
Thank you very much for your reply. 

Yes, I am currently developing an environment wrapper on isaac, but I've found that Isaac simulator lacks a function similar to `reset_to`, which allows setting the simulator state to a specified state (a feature provided by Mujoco). This capability is required by Mimicgen for data generation, as seen in `mimicgen/scripts/prepare_src_datasets.py at line 75: env.reset_to({"states" : states[t]}`). Do you have any suggestions on how to address this limitation?

Thank you in advance for your help.

**Comment by amandlek** [comment]
I'm not an expert on Isaac Sim so I'm not sure about this. However, one potential temporary workaround could be to collect the information needed by MimicGen during teleoperation itself, so you don't need the separate extraction process that happens in prepare_src_datasets.py

**Comment by iamanshulchauhan1** [comment]
@GuaguaguaLiu Hey I am also trying to use the Issac for my project, so I am just wondering if you could develop that environment wrapper for Issac?
