### ISSUE TITLE
How can collect data that is continuous and free of pauses ?

### ISSUE THREAD

**Issue by GuaguaguaLiu** [NVlabs/mimicgen#26]
Hello,

Thanks for your great work.  

While reviewing the original teleoperation data from MimicGen, I noticed that the actions are continuous and there is no indication of pauses or waiting during the operations. For instance, in the `pick_place.hdf5 ` file, the action data appears as follows: 
```
[[ 9.40000000e-02 -5.40000000e-02 -7.20000000e-02 -2.75502633e-03
   5.05185463e-02 -1.73601076e-01 -1.00000000e+00]
 [ 2.51000000e-01 -1.30000000e-01 -1.55000000e-01 -1.28551386e-03
   4.42666449e-02 -1.66325152e-01 -1.00000000e+00]
   ...]. 
```

However, when I follow the instructions in Robosuite to collect teleoperation data using the keyboard, I find that the actions are discrete and it is inevitable to have human-induced pauses. The action data looks like this: 
```
[[0., 0., 0., 0., 0., 0., 1.],
 [0., 0., 0., 0., 0., 0., 1.],
[0., 0., 0., 0., 0., 0., 1.]
 [0., 0., 0., 0.4, 0., 0., 1.]
[0., 0., 0., 0.4, 0., 0., 1.]
 ...] 
```

I would like to know how I can collect data that is continuous and free of pauses, similar to mimicgen's. I look forward to your reply.

Thank you.

**Comment by amandlek** [comment]
I strongly suggest using the spacemouse interface (see [here](https://robosuite.ai/docs/algorithms/demonstrations.html#dconnexion-spacemouse-controls)) for demonstration collection -- the keyboard interface definitely suffers from pauses and might cause difficulties for policy learning.
