### ISSUE TITLE
How would I be able to add distractor objects to an Enviorment?

### ISSUE THREAD

**Issue by MasonJohnHawver42** [NVlabs/mimicgen#33]
I want to be able to create an environment that has distractor objects, so that I can train on a cannotical environment without them then test on an environment that then has them?

What guides and documentation should I look at to achieve this?

All the best,
MJH

**Comment by amandlek** [comment]
Great question - assuming that you are planning to use the robosuite environments in this repository, I would recommend subclassing the relevant environment class, and adding the distractor objects in the subclass. Then, you can use the source demonstrations collected on the original environment to generate data for the new subclass environment. For some more guidance on working with robosuite I'd suggest reading their [documentation](https://robosuite.ai/docs/overview.html).
