### ISSUE TITLE
Is it possible to generate data based on inverse kinematics?

### ISSUE THREAD

**Issue by gadorneles** [NVlabs/mimicgen#34]
I want to generate a few demos (around 10) without using teleoperation. My initial solution is using a franka emika panda controller to define a grasp point and get the demos from the successful runs.

 Has this been done before? Would the simulation support it?

**Comment by amandlek** [comment]
As long as you can provide source demonstrations in the same format expected by MimicGen, this should be fine. As for the simulation supporting it, that would be a better question for the issues page of simulation framework that you choose to use
