### ISSUE TITLE
Generated trajectories are unsteady

### ISSUE THREAD

**Issue by gadorneles** [NVlabs/mimicgen#35]
Hello, I was able to generate a dataset based on a few demonstrations I made on a custom task environment. The custom task was very simple, basic only lifting an object by grabbing an specific handle. However, the robot is shaking while executing the movements, which did not happen in the original dataset. Any ideas to what could have introduced this issue? I'll gladly elaborate on more details of my implementation if necessary.

Video example of what I mean can be seen below:

https://github.com/user-attachments/assets/2484b15e-7139-4e6d-8672-6499235eb67d

**Comment by amandlek** [comment]
We add action noise by default to improve the policy learning success rate. You can reduce the magnitude of the noise or set it to zero to disable it completely in the MimicGen config - for example [here](https://github.com/NVlabs/mimicgen/blob/042ed06ba885102a93738c000b7066528ac2d714/mimicgen/configs/robosuite.py#L49).
