### ISSUE TITLE
Not compatible with robosuite v1.5

### ISSUE THREAD

**Issue by Felix-Zhenghao** [NVlabs/mimicgen#37]
As the main branch of `robosuite`  has been updated to v1.5, the import paths of multiple files do not work. For instance, the error when running `python demo_random_action.py` will be:

```
[robosuite WARNING] Could not import robosuite_models. Some robots may not be available. If you want to use these robots, please install robosuite_models from source (https://github.com/ARISE-Initiative/robosuite_models) or through pip install. (__init__.py:30)
Traceback (most recent call last):
  File "/Users/felix020422/Desktop/robotDB/mimicgen/mimicgen/scripts/demo_random_action.py", line 9, in <module>
    from robosuite.controllers import load_controller_config
ImportError: cannot import name 'load_controller_config' from 'robosuite.controllers' (/Users/felix020422/Desktop/robotDB/robosuite/robosuite/controllers/__init__.py)
```

In the mimicgen doc, there may well be a sentence 'please run `git checkout v1.4`' inside the robosuite directory.

**Comment by Felix-Zhenghao** [comment]
After checking out to the `v1.4` branch, mimicgen works on my Mac.

**Comment by amandlek** [comment]
Yes this is expected - we haven't made the changes to support `v1.5` yet. We have a note in the docs here: https://mimicgen.github.io/docs/introduction/installation.html#robosuite

**Comment by lrenaux-bdai** [comment]
> Yes this is expected - we haven't made the changes to support `v1.5` yet. We have a note in the docs here: https://mimicgen.github.io/docs/introduction/installation.html#robosuite

Is there a plan to update to 1.5 in the near future?
