### ISSUE TITLE
AttributeError: module 'robosuite' has no attribute 'ALL_ENVIRONMENTS'

### ISSUE THREAD

**Issue by Charlie0257** [NVlabs/mimicgen#4]
Hi, @aflat 
Thanks for the great work!

When I tried the command `python demo_random_action.py`, the error occurred as follows——
`Traceback (most recent call last):`
  `File "demo_random_action.py", line 64, in <module>`
    `options["env_name"] = choose_mimicgen_environment()`
  `File "demo_random_action.py", line 28, in choose_mimicgen_environment`
    `robosuite_envs = set(suite.ALL_ENVIRONMENTS)`
`AttributeError: module 'robosuite' has no attribute 'ALL_ENVIRONMENTS'`

I guess I installed the wrong level under the mimicgen_environments, which means it can't be imported :(
This is my file tree：
—mimicgen_environments
   —robosuite
   —robomimic
   —robosuite-task-zoo

Could you provide the solution or an example for installing these packages?

Thanks for any help!

**Comment by crazybirl** [comment]
@Charlie0257 emm, same error. Have you solved it?

**Comment by Charlie0257** [comment]
@crazybirl I solved this error by downloading Robosuite, Robomimic, and Robosuite-task-zoo under the file mimicgen_`environments/mimicgen_envs`.

**Comment by crazybirl** [comment]
Thanks for your help! It works well. The work is a huge contribution and very useful for me, thanks a lot again.




Liu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/mimicgen_environments"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/mimicgen_environments] AttributeError: module 'robosuite' has no attribute 'ALL_ENVIRONMENTS' (Issue #4)





 
@crazybirl I solved this error by downloading Robosuite, Robomimic, and Robosuite-task-zoo under the file mimicgen_environments/mimicgen_envs.

**Comment by amandlek** [comment]
Hi @Charlie0257 @crazybirl ,

Thanks for sharing this issue. Can you share more precise instructions on reproducing the issue? I'm not seeing any problems on my end.

Specifically, what is your precise folder structure - where exactly did you place the robosuite repo? And did you make sure to install from source? One other test is to open up a python shell and type `import robosuite; print(robosuite.__path__)` to verify the location of the module is where you expect.

**Comment by shmooWang** [comment]
> @crazybirl I solved this error by downloading Robosuite, Robomimic, and Robosuite-task-zoo under the file mimicgen_`environments/mimicgen_envs`.

Thank you very much, this solves the problem. But why is that?
